/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cctp from "./cctp";
export type { cctp };
import type * as test from "./test";
export type { test };
export type { StableNaira } from "./StableNaira";
export type { StableNairaPriceOracle } from "./StableNairaPriceOracle";
export type { StableNairaUUPSDeployer } from "./StableNairaUUPSDeployer";
