/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface StableNairaPriceOracleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_DEVIATION_PPB"
      | "MAX_STALENESS_SEC"
      | "MIN_DEVIATION_PPB"
      | "MIN_STALENESS_SEC"
      | "_reportHash"
      | "acceptOwnership"
      | "activeReporterCount"
      | "addReporter"
      | "decimals"
      | "getLatestPrice"
      | "getReporters"
      | "isReporter"
      | "latestRoundId"
      | "maxDeviationPPB"
      | "maxStalenessSec"
      | "owner"
      | "pendingOwner"
      | "quorum"
      | "removeReporter"
      | "renounceOwnership"
      | "reporters"
      | "rounds"
      | "setMaxDeviationPPB"
      | "setMaxStaleness"
      | "setQuorum"
      | "submitReport"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MaxDeviationPPBUpdated"
      | "MaxStalenessUpdated"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "PriceSubmitted"
      | "QuorumUpdated"
      | "ReporterAdded"
      | "ReporterRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_DEVIATION_PPB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_STALENESS_SEC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_DEVIATION_PPB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_STALENESS_SEC",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "_reportHash",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "activeReporterCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getLatestPrice",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReporters",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "latestRoundId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxDeviationPPB",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxStalenessSec",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "quorum", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeReporter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reporters",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rounds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxDeviationPPB",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxStaleness",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setQuorum",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitReport",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_DEVIATION_PPB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_STALENESS_SEC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_DEVIATION_PPB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_STALENESS_SEC",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "_reportHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "activeReporterCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLatestPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReporters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isReporter", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "latestRoundId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxDeviationPPB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxStalenessSec",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quorum", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeReporter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reporters", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "rounds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxDeviationPPB",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxStaleness",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setQuorum", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitReport",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace MaxDeviationPPBUpdatedEvent {
  export type InputTuple = [previous: BigNumberish, current: BigNumberish];
  export type OutputTuple = [previous: bigint, current: bigint];
  export interface OutputObject {
    previous: bigint;
    current: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxStalenessUpdatedEvent {
  export type InputTuple = [previous: BigNumberish, current: BigNumberish];
  export type OutputTuple = [previous: bigint, current: bigint];
  export interface OutputObject {
    previous: bigint;
    current: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PriceSubmittedEvent {
  export type InputTuple = [
    roundId: BigNumberish,
    price: BigNumberish,
    timestamp: BigNumberish,
    submittedBy: AddressLike
  ];
  export type OutputTuple = [
    roundId: bigint,
    price: bigint,
    timestamp: bigint,
    submittedBy: string
  ];
  export interface OutputObject {
    roundId: bigint;
    price: bigint;
    timestamp: bigint;
    submittedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace QuorumUpdatedEvent {
  export type InputTuple = [previous: BigNumberish, current: BigNumberish];
  export type OutputTuple = [previous: bigint, current: bigint];
  export interface OutputObject {
    previous: bigint;
    current: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReporterAddedEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReporterRemovedEvent {
  export type InputTuple = [reporter: AddressLike];
  export type OutputTuple = [reporter: string];
  export interface OutputObject {
    reporter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StableNairaPriceOracle extends BaseContract {
  connect(runner?: ContractRunner | null): StableNairaPriceOracle;
  waitForDeployment(): Promise<this>;

  interface: StableNairaPriceOracleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_DEVIATION_PPB: TypedContractMethod<[], [bigint], "view">;

  MAX_STALENESS_SEC: TypedContractMethod<[], [bigint], "view">;

  MIN_DEVIATION_PPB: TypedContractMethod<[], [bigint], "view">;

  MIN_STALENESS_SEC: TypedContractMethod<[], [bigint], "view">;

  _reportHash: TypedContractMethod<
    [roundId: BigNumberish, price: BigNumberish, timestamp: BigNumberish],
    [string],
    "view"
  >;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  activeReporterCount: TypedContractMethod<[], [bigint], "view">;

  addReporter: TypedContractMethod<[r: AddressLike], [void], "nonpayable">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  getLatestPrice: TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { price: bigint; ts: bigint; roundId: bigint }],
    "view"
  >;

  getReporters: TypedContractMethod<[], [string[]], "view">;

  isReporter: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  latestRoundId: TypedContractMethod<[], [bigint], "view">;

  maxDeviationPPB: TypedContractMethod<[], [bigint], "view">;

  maxStalenessSec: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  quorum: TypedContractMethod<[], [bigint], "view">;

  removeReporter: TypedContractMethod<[r: AddressLike], [void], "nonpayable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reporters: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  rounds: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        roundId: bigint;
        price: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;

  setMaxDeviationPPB: TypedContractMethod<
    [ppb: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMaxStaleness: TypedContractMethod<
    [sec_: BigNumberish],
    [void],
    "nonpayable"
  >;

  setQuorum: TypedContractMethod<[q: BigNumberish], [void], "nonpayable">;

  submitReport: TypedContractMethod<
    [
      roundId: BigNumberish,
      price: BigNumberish,
      timestamp: BigNumberish,
      sigs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_DEVIATION_PPB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_STALENESS_SEC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_DEVIATION_PPB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_STALENESS_SEC"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "_reportHash"
  ): TypedContractMethod<
    [roundId: BigNumberish, price: BigNumberish, timestamp: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "activeReporterCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addReporter"
  ): TypedContractMethod<[r: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestPrice"
  ): TypedContractMethod<
    [],
    [[bigint, bigint, bigint] & { price: bigint; ts: bigint; roundId: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReporters"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "isReporter"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "latestRoundId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxDeviationPPB"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxStalenessSec"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quorum"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "removeReporter"
  ): TypedContractMethod<[r: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reporters"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "rounds"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint] & {
        roundId: bigint;
        price: bigint;
        timestamp: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMaxDeviationPPB"
  ): TypedContractMethod<[ppb: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMaxStaleness"
  ): TypedContractMethod<[sec_: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setQuorum"
  ): TypedContractMethod<[q: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitReport"
  ): TypedContractMethod<
    [
      roundId: BigNumberish,
      price: BigNumberish,
      timestamp: BigNumberish,
      sigs: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "MaxDeviationPPBUpdated"
  ): TypedContractEvent<
    MaxDeviationPPBUpdatedEvent.InputTuple,
    MaxDeviationPPBUpdatedEvent.OutputTuple,
    MaxDeviationPPBUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MaxStalenessUpdated"
  ): TypedContractEvent<
    MaxStalenessUpdatedEvent.InputTuple,
    MaxStalenessUpdatedEvent.OutputTuple,
    MaxStalenessUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PriceSubmitted"
  ): TypedContractEvent<
    PriceSubmittedEvent.InputTuple,
    PriceSubmittedEvent.OutputTuple,
    PriceSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "QuorumUpdated"
  ): TypedContractEvent<
    QuorumUpdatedEvent.InputTuple,
    QuorumUpdatedEvent.OutputTuple,
    QuorumUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReporterAdded"
  ): TypedContractEvent<
    ReporterAddedEvent.InputTuple,
    ReporterAddedEvent.OutputTuple,
    ReporterAddedEvent.OutputObject
  >;
  getEvent(
    key: "ReporterRemoved"
  ): TypedContractEvent<
    ReporterRemovedEvent.InputTuple,
    ReporterRemovedEvent.OutputTuple,
    ReporterRemovedEvent.OutputObject
  >;

  filters: {
    "MaxDeviationPPBUpdated(uint256,uint256)": TypedContractEvent<
      MaxDeviationPPBUpdatedEvent.InputTuple,
      MaxDeviationPPBUpdatedEvent.OutputTuple,
      MaxDeviationPPBUpdatedEvent.OutputObject
    >;
    MaxDeviationPPBUpdated: TypedContractEvent<
      MaxDeviationPPBUpdatedEvent.InputTuple,
      MaxDeviationPPBUpdatedEvent.OutputTuple,
      MaxDeviationPPBUpdatedEvent.OutputObject
    >;

    "MaxStalenessUpdated(uint256,uint256)": TypedContractEvent<
      MaxStalenessUpdatedEvent.InputTuple,
      MaxStalenessUpdatedEvent.OutputTuple,
      MaxStalenessUpdatedEvent.OutputObject
    >;
    MaxStalenessUpdated: TypedContractEvent<
      MaxStalenessUpdatedEvent.InputTuple,
      MaxStalenessUpdatedEvent.OutputTuple,
      MaxStalenessUpdatedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PriceSubmitted(uint256,uint256,uint256,address)": TypedContractEvent<
      PriceSubmittedEvent.InputTuple,
      PriceSubmittedEvent.OutputTuple,
      PriceSubmittedEvent.OutputObject
    >;
    PriceSubmitted: TypedContractEvent<
      PriceSubmittedEvent.InputTuple,
      PriceSubmittedEvent.OutputTuple,
      PriceSubmittedEvent.OutputObject
    >;

    "QuorumUpdated(uint256,uint256)": TypedContractEvent<
      QuorumUpdatedEvent.InputTuple,
      QuorumUpdatedEvent.OutputTuple,
      QuorumUpdatedEvent.OutputObject
    >;
    QuorumUpdated: TypedContractEvent<
      QuorumUpdatedEvent.InputTuple,
      QuorumUpdatedEvent.OutputTuple,
      QuorumUpdatedEvent.OutputObject
    >;

    "ReporterAdded(address)": TypedContractEvent<
      ReporterAddedEvent.InputTuple,
      ReporterAddedEvent.OutputTuple,
      ReporterAddedEvent.OutputObject
    >;
    ReporterAdded: TypedContractEvent<
      ReporterAddedEvent.InputTuple,
      ReporterAddedEvent.OutputTuple,
      ReporterAddedEvent.OutputObject
    >;

    "ReporterRemoved(address)": TypedContractEvent<
      ReporterRemovedEvent.InputTuple,
      ReporterRemovedEvent.OutputTuple,
      ReporterRemovedEvent.OutputObject
    >;
    ReporterRemoved: TypedContractEvent<
      ReporterRemovedEvent.InputTuple,
      ReporterRemovedEvent.OutputTuple,
      ReporterRemovedEvent.OutputObject
    >;
  };
}
