[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crypto_parity = "77dv5m4NUhEDX768Kt1bgkAu34nxaZ51sPhNzN6hamik"
message_transmitter = "6DV1hTBVf6Ks9mguQiVY82B5uGPQS2nHddzgL3GhFaWe"
stable_naira = "7EXTBay4r4Ft3k5poXnhxMCQXe5s5yv2kfxMiA7babYD"
token_messenger = "AcKeZENGFRMxm3rtQg3chAiwf24d992Ljj574i937jjv"
validator_registry = "GGMoxtodCLEvPB3HuDJcS3kcS6JVpmfBQEHYfoUPe7kR"

[programs.devnet]
crypto_parity = "77dv5m4NUhEDX768Kt1bgkAu34nxaZ51sPhNzN6hamik"
message_transmitter = "6DV1hTBVf6Ks9mguQiVY82B5uGPQS2nHddzgL3GhFaWe"
stable_naira = "7EXTBay4r4Ft3k5poXnhxMCQXe5s5yv2kfxMiA7babYD"
token_messenger = "AcKeZENGFRMxm3rtQg3chAiwf24d992Ljj574i937jjv"
validator_registry = "GGMoxtodCLEvPB3HuDJcS3kcS6JVpmfBQEHYfoUPe7kR"

[programs.mainnet]
crypto_parity = "77dv5m4NUhEDX768Kt1bgkAu34nxaZ51sPhNzN6hamik"
message_transmitter = "6DV1hTBVf6Ks9mguQiVY82B5uGPQS2nHddzgL3GhFaWe"
stable_naira = "7EXTBay4r4Ft3k5poXnhxMCQXe5s5yv2kfxMiA7babYD"
token_messenger = "AcKeZENGFRMxm3rtQg3chAiwf24d992Ljj574i937jjv"
validator_registry = "GGMoxtodCLEvPB3HuDJcS3kcS6JVpmfBQEHYfoUPe7kR"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
