[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
crypto_parity = "6VHLvJDTt5vCmPgPfa2PgW4TXsWFgbUSAbiesfYFa2h6"
stable_naira = "BYB7RM7d4WeUWJd6xXDFZFqAEbbDa2Ezt718hpZG3eoG"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
