/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TimelockedUpgradeable {
  export type PendingActionStruct = {
    actionHash: BytesLike;
    eta: BigNumberish;
  };

  export type PendingActionStructOutput = [actionHash: string, eta: bigint] & {
    actionHash: string;
    eta: bigint;
  };
}

export interface MessageTransmitterInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_TIMELOCK"
      | "MIN_FLOOR_TIMELOCK"
      | "MIN_MAX_BODY_SIZE"
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptOwnership"
      | "cancel"
      | "commitSetSignatureVerifier"
      | "commitUpgrade"
      | "initialize"
      | "isNonceUsed"
      | "localDomain"
      | "maxMessageBodySize"
      | "minTimelock"
      | "nextAvailableNonce"
      | "owner"
      | "pause"
      | "paused"
      | "pendingAction"
      | "pendingOwner"
      | "proxiableUUID"
      | "queueSetSignatureVerifier"
      | "queueUpgrade"
      | "receiveMessage"
      | "renounceOwnership"
      | "sendMessage"
      | "sendMessageWithCaller"
      | "setMaxMessageBodySize"
      | "setMinTimelock"
      | "setTimelock"
      | "signatureVerifier"
      | "timelock"
      | "transferOwnership"
      | "unpause"
      | "upgradeToAndCall"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionCancelled"
      | "ActionCommitted"
      | "ActionQueued"
      | "Initialized"
      | "MaxMessageBodySizeUpdated"
      | "MessageReceived"
      | "MessageSent"
      | "MinTimelockUpdated"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "SignatureVerifierUpdated"
      | "TimelockUpdated"
      | "Unpaused"
      | "UpgradeCommitted"
      | "UpgradeQueued"
      | "Upgraded"
      | "VerifierChangeCommitted"
      | "VerifierChangeQueued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_TIMELOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_FLOOR_TIMELOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_MAX_BODY_SIZE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitSetSignatureVerifier",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitUpgrade",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      AddressLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "isNonceUsed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "localDomain",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "maxMessageBodySize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTimelock",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextAvailableNonce",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingAction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "queueSetSignatureVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queueUpgrade",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiveMessage",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessage",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sendMessageWithCaller",
    values: [BigNumberish, BytesLike, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMaxMessageBodySize",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setMinTimelock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "signatureVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "MAX_TIMELOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_FLOOR_TIMELOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_MAX_BODY_SIZE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitSetSignatureVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isNonceUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "localDomain",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "maxMessageBodySize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextAvailableNonce",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueSetSignatureVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiveMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sendMessageWithCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMaxMessageBodySize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "signatureVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace ActionCancelledEvent {
  export type InputTuple = [actionId: BigNumberish, actionHash: BytesLike];
  export type OutputTuple = [actionId: bigint, actionHash: string];
  export interface OutputObject {
    actionId: bigint;
    actionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionCommittedEvent {
  export type InputTuple = [actionId: BigNumberish, actionHash: BytesLike];
  export type OutputTuple = [actionId: bigint, actionHash: string];
  export interface OutputObject {
    actionId: bigint;
    actionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionQueuedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    actionHash: BytesLike,
    eta: BigNumberish
  ];
  export type OutputTuple = [actionId: bigint, actionHash: string, eta: bigint];
  export interface OutputObject {
    actionId: bigint;
    actionHash: string;
    eta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxMessageBodySizeUpdatedEvent {
  export type InputTuple = [previous: BigNumberish, current: BigNumberish];
  export type OutputTuple = [previous: bigint, current: bigint];
  export interface OutputObject {
    previous: bigint;
    current: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageReceivedEvent {
  export type InputTuple = [
    caller: AddressLike,
    sourceDomain: BigNumberish,
    nonce: BigNumberish,
    sender: BytesLike,
    messageBody: BytesLike
  ];
  export type OutputTuple = [
    caller: string,
    sourceDomain: bigint,
    nonce: bigint,
    sender: string,
    messageBody: string
  ];
  export interface OutputObject {
    caller: string;
    sourceDomain: bigint;
    nonce: bigint;
    sender: string;
    messageBody: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageSentEvent {
  export type InputTuple = [message: BytesLike];
  export type OutputTuple = [message: string];
  export interface OutputObject {
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinTimelockUpdatedEvent {
  export type InputTuple = [previous: BigNumberish, current: BigNumberish];
  export type OutputTuple = [previous: bigint, current: bigint];
  export interface OutputObject {
    previous: bigint;
    current: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SignatureVerifierUpdatedEvent {
  export type InputTuple = [previous: AddressLike, current: AddressLike];
  export type OutputTuple = [previous: string, current: string];
  export interface OutputObject {
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockUpdatedEvent {
  export type InputTuple = [previous: BigNumberish, current: BigNumberish];
  export type OutputTuple = [previous: bigint, current: bigint];
  export interface OutputObject {
    previous: bigint;
    current: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeCommittedEvent {
  export type InputTuple = [actionId: BigNumberish, newImpl: AddressLike];
  export type OutputTuple = [actionId: bigint, newImpl: string];
  export interface OutputObject {
    actionId: bigint;
    newImpl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeQueuedEvent {
  export type InputTuple = [actionId: BigNumberish, newImpl: AddressLike];
  export type OutputTuple = [actionId: bigint, newImpl: string];
  export interface OutputObject {
    actionId: bigint;
    newImpl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierChangeCommittedEvent {
  export type InputTuple = [actionId: BigNumberish, newVerifier: AddressLike];
  export type OutputTuple = [actionId: bigint, newVerifier: string];
  export interface OutputObject {
    actionId: bigint;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierChangeQueuedEvent {
  export type InputTuple = [actionId: BigNumberish, newVerifier: AddressLike];
  export type OutputTuple = [actionId: bigint, newVerifier: string];
  export interface OutputObject {
    actionId: bigint;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MessageTransmitter extends BaseContract {
  connect(runner?: ContractRunner | null): MessageTransmitter;
  waitForDeployment(): Promise<this>;

  interface: MessageTransmitterInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  MIN_FLOOR_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  MIN_MAX_BODY_SIZE: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  cancel: TypedContractMethod<[actionId: BigNumberish], [void], "nonpayable">;

  commitSetSignatureVerifier: TypedContractMethod<
    [actionId: BigNumberish, newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  commitUpgrade: TypedContractMethod<
    [actionId: BigNumberish, newImpl: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      localDomain_: BigNumberish,
      signatureVerifier_: AddressLike,
      maxMessageBodySize_: BigNumberish,
      owner_: AddressLike,
      initialTimelock: BigNumberish,
      initialMinTimelock: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  isNonceUsed: TypedContractMethod<
    [sourceDomain: BigNumberish, nonce: BigNumberish],
    [boolean],
    "view"
  >;

  localDomain: TypedContractMethod<[], [bigint], "view">;

  maxMessageBodySize: TypedContractMethod<[], [bigint], "view">;

  minTimelock: TypedContractMethod<[], [bigint], "view">;

  nextAvailableNonce: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingAction: TypedContractMethod<
    [actionId: BigNumberish],
    [TimelockedUpgradeable.PendingActionStructOutput],
    "view"
  >;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  queueSetSignatureVerifier: TypedContractMethod<
    [newVerifier: AddressLike],
    [bigint],
    "nonpayable"
  >;

  queueUpgrade: TypedContractMethod<
    [newImpl: AddressLike, data: BytesLike],
    [bigint],
    "nonpayable"
  >;

  receiveMessage: TypedContractMethod<
    [message: BytesLike, attestation: BytesLike],
    [boolean],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  sendMessage: TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      messageBody: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  sendMessageWithCaller: TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      destinationCaller: BytesLike,
      messageBody: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  setMaxMessageBodySize: TypedContractMethod<
    [newMax: BigNumberish],
    [void],
    "nonpayable"
  >;

  setMinTimelock: TypedContractMethod<
    [newMin: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTimelock: TypedContractMethod<[newTl: BigNumberish], [void], "nonpayable">;

  signatureVerifier: TypedContractMethod<[], [string], "view">;

  timelock: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  version: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_FLOOR_TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_MAX_BODY_SIZE"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[actionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitSetSignatureVerifier"
  ): TypedContractMethod<
    [actionId: BigNumberish, newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitUpgrade"
  ): TypedContractMethod<
    [actionId: BigNumberish, newImpl: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      localDomain_: BigNumberish,
      signatureVerifier_: AddressLike,
      maxMessageBodySize_: BigNumberish,
      owner_: AddressLike,
      initialTimelock: BigNumberish,
      initialMinTimelock: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isNonceUsed"
  ): TypedContractMethod<
    [sourceDomain: BigNumberish, nonce: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "localDomain"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxMessageBodySize"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "minTimelock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextAvailableNonce"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingAction"
  ): TypedContractMethod<
    [actionId: BigNumberish],
    [TimelockedUpgradeable.PendingActionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "queueSetSignatureVerifier"
  ): TypedContractMethod<[newVerifier: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "queueUpgrade"
  ): TypedContractMethod<
    [newImpl: AddressLike, data: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "receiveMessage"
  ): TypedContractMethod<
    [message: BytesLike, attestation: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sendMessage"
  ): TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      messageBody: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sendMessageWithCaller"
  ): TypedContractMethod<
    [
      destinationDomain: BigNumberish,
      recipient: BytesLike,
      destinationCaller: BytesLike,
      messageBody: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setMaxMessageBodySize"
  ): TypedContractMethod<[newMax: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinTimelock"
  ): TypedContractMethod<[newMin: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTimelock"
  ): TypedContractMethod<[newTl: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "signatureVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "ActionCancelled"
  ): TypedContractEvent<
    ActionCancelledEvent.InputTuple,
    ActionCancelledEvent.OutputTuple,
    ActionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ActionCommitted"
  ): TypedContractEvent<
    ActionCommittedEvent.InputTuple,
    ActionCommittedEvent.OutputTuple,
    ActionCommittedEvent.OutputObject
  >;
  getEvent(
    key: "ActionQueued"
  ): TypedContractEvent<
    ActionQueuedEvent.InputTuple,
    ActionQueuedEvent.OutputTuple,
    ActionQueuedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "MaxMessageBodySizeUpdated"
  ): TypedContractEvent<
    MaxMessageBodySizeUpdatedEvent.InputTuple,
    MaxMessageBodySizeUpdatedEvent.OutputTuple,
    MaxMessageBodySizeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MessageReceived"
  ): TypedContractEvent<
    MessageReceivedEvent.InputTuple,
    MessageReceivedEvent.OutputTuple,
    MessageReceivedEvent.OutputObject
  >;
  getEvent(
    key: "MessageSent"
  ): TypedContractEvent<
    MessageSentEvent.InputTuple,
    MessageSentEvent.OutputTuple,
    MessageSentEvent.OutputObject
  >;
  getEvent(
    key: "MinTimelockUpdated"
  ): TypedContractEvent<
    MinTimelockUpdatedEvent.InputTuple,
    MinTimelockUpdatedEvent.OutputTuple,
    MinTimelockUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "SignatureVerifierUpdated"
  ): TypedContractEvent<
    SignatureVerifierUpdatedEvent.InputTuple,
    SignatureVerifierUpdatedEvent.OutputTuple,
    SignatureVerifierUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockUpdated"
  ): TypedContractEvent<
    TimelockUpdatedEvent.InputTuple,
    TimelockUpdatedEvent.OutputTuple,
    TimelockUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeCommitted"
  ): TypedContractEvent<
    UpgradeCommittedEvent.InputTuple,
    UpgradeCommittedEvent.OutputTuple,
    UpgradeCommittedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeQueued"
  ): TypedContractEvent<
    UpgradeQueuedEvent.InputTuple,
    UpgradeQueuedEvent.OutputTuple,
    UpgradeQueuedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierChangeCommitted"
  ): TypedContractEvent<
    VerifierChangeCommittedEvent.InputTuple,
    VerifierChangeCommittedEvent.OutputTuple,
    VerifierChangeCommittedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierChangeQueued"
  ): TypedContractEvent<
    VerifierChangeQueuedEvent.InputTuple,
    VerifierChangeQueuedEvent.OutputTuple,
    VerifierChangeQueuedEvent.OutputObject
  >;

  filters: {
    "ActionCancelled(uint256,bytes32)": TypedContractEvent<
      ActionCancelledEvent.InputTuple,
      ActionCancelledEvent.OutputTuple,
      ActionCancelledEvent.OutputObject
    >;
    ActionCancelled: TypedContractEvent<
      ActionCancelledEvent.InputTuple,
      ActionCancelledEvent.OutputTuple,
      ActionCancelledEvent.OutputObject
    >;

    "ActionCommitted(uint256,bytes32)": TypedContractEvent<
      ActionCommittedEvent.InputTuple,
      ActionCommittedEvent.OutputTuple,
      ActionCommittedEvent.OutputObject
    >;
    ActionCommitted: TypedContractEvent<
      ActionCommittedEvent.InputTuple,
      ActionCommittedEvent.OutputTuple,
      ActionCommittedEvent.OutputObject
    >;

    "ActionQueued(uint256,bytes32,uint64)": TypedContractEvent<
      ActionQueuedEvent.InputTuple,
      ActionQueuedEvent.OutputTuple,
      ActionQueuedEvent.OutputObject
    >;
    ActionQueued: TypedContractEvent<
      ActionQueuedEvent.InputTuple,
      ActionQueuedEvent.OutputTuple,
      ActionQueuedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "MaxMessageBodySizeUpdated(uint256,uint256)": TypedContractEvent<
      MaxMessageBodySizeUpdatedEvent.InputTuple,
      MaxMessageBodySizeUpdatedEvent.OutputTuple,
      MaxMessageBodySizeUpdatedEvent.OutputObject
    >;
    MaxMessageBodySizeUpdated: TypedContractEvent<
      MaxMessageBodySizeUpdatedEvent.InputTuple,
      MaxMessageBodySizeUpdatedEvent.OutputTuple,
      MaxMessageBodySizeUpdatedEvent.OutputObject
    >;

    "MessageReceived(address,uint32,uint64,bytes32,bytes)": TypedContractEvent<
      MessageReceivedEvent.InputTuple,
      MessageReceivedEvent.OutputTuple,
      MessageReceivedEvent.OutputObject
    >;
    MessageReceived: TypedContractEvent<
      MessageReceivedEvent.InputTuple,
      MessageReceivedEvent.OutputTuple,
      MessageReceivedEvent.OutputObject
    >;

    "MessageSent(bytes)": TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;
    MessageSent: TypedContractEvent<
      MessageSentEvent.InputTuple,
      MessageSentEvent.OutputTuple,
      MessageSentEvent.OutputObject
    >;

    "MinTimelockUpdated(uint256,uint256)": TypedContractEvent<
      MinTimelockUpdatedEvent.InputTuple,
      MinTimelockUpdatedEvent.OutputTuple,
      MinTimelockUpdatedEvent.OutputObject
    >;
    MinTimelockUpdated: TypedContractEvent<
      MinTimelockUpdatedEvent.InputTuple,
      MinTimelockUpdatedEvent.OutputTuple,
      MinTimelockUpdatedEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "SignatureVerifierUpdated(address,address)": TypedContractEvent<
      SignatureVerifierUpdatedEvent.InputTuple,
      SignatureVerifierUpdatedEvent.OutputTuple,
      SignatureVerifierUpdatedEvent.OutputObject
    >;
    SignatureVerifierUpdated: TypedContractEvent<
      SignatureVerifierUpdatedEvent.InputTuple,
      SignatureVerifierUpdatedEvent.OutputTuple,
      SignatureVerifierUpdatedEvent.OutputObject
    >;

    "TimelockUpdated(uint256,uint256)": TypedContractEvent<
      TimelockUpdatedEvent.InputTuple,
      TimelockUpdatedEvent.OutputTuple,
      TimelockUpdatedEvent.OutputObject
    >;
    TimelockUpdated: TypedContractEvent<
      TimelockUpdatedEvent.InputTuple,
      TimelockUpdatedEvent.OutputTuple,
      TimelockUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UpgradeCommitted(uint256,address)": TypedContractEvent<
      UpgradeCommittedEvent.InputTuple,
      UpgradeCommittedEvent.OutputTuple,
      UpgradeCommittedEvent.OutputObject
    >;
    UpgradeCommitted: TypedContractEvent<
      UpgradeCommittedEvent.InputTuple,
      UpgradeCommittedEvent.OutputTuple,
      UpgradeCommittedEvent.OutputObject
    >;

    "UpgradeQueued(uint256,address)": TypedContractEvent<
      UpgradeQueuedEvent.InputTuple,
      UpgradeQueuedEvent.OutputTuple,
      UpgradeQueuedEvent.OutputObject
    >;
    UpgradeQueued: TypedContractEvent<
      UpgradeQueuedEvent.InputTuple,
      UpgradeQueuedEvent.OutputTuple,
      UpgradeQueuedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "VerifierChangeCommitted(uint256,address)": TypedContractEvent<
      VerifierChangeCommittedEvent.InputTuple,
      VerifierChangeCommittedEvent.OutputTuple,
      VerifierChangeCommittedEvent.OutputObject
    >;
    VerifierChangeCommitted: TypedContractEvent<
      VerifierChangeCommittedEvent.InputTuple,
      VerifierChangeCommittedEvent.OutputTuple,
      VerifierChangeCommittedEvent.OutputObject
    >;

    "VerifierChangeQueued(uint256,address)": TypedContractEvent<
      VerifierChangeQueuedEvent.InputTuple,
      VerifierChangeQueuedEvent.OutputTuple,
      VerifierChangeQueuedEvent.OutputObject
    >;
    VerifierChangeQueued: TypedContractEvent<
      VerifierChangeQueuedEvent.InputTuple,
      VerifierChangeQueuedEvent.OutputTuple,
      VerifierChangeQueuedEvent.OutputObject
    >;
  };
}
