/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace TimelockedUpgradeable {
  export type PendingActionStruct = {
    actionHash: BytesLike;
    eta: BigNumberish;
  };

  export type PendingActionStructOutput = [actionHash: string, eta: bigint] & {
    actionHash: string;
    eta: bigint;
  };
}

export interface TokenMessengerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "MAX_FEE_BPS"
      | "MAX_TIMELOCK"
      | "MIN_FLOOR_TIMELOCK"
      | "UPGRADE_INTERFACE_VERSION"
      | "acceptOwnership"
      | "bodyVersion"
      | "cancel"
      | "commitSetFeeConfig"
      | "commitSetLocalToken"
      | "commitSetMessageTransmitter"
      | "commitSetRemoteRouter"
      | "commitUpgrade"
      | "depositForBurn"
      | "depositForBurnWithCaller"
      | "feeBps"
      | "feeRecipient"
      | "handleReceiveMessage"
      | "initialize"
      | "localToken"
      | "messageTransmitter"
      | "minTimelock"
      | "owner"
      | "pause"
      | "paused"
      | "pendingAction"
      | "pendingOwner"
      | "proxiableUUID"
      | "queueSetFeeConfig"
      | "queueSetLocalToken"
      | "queueSetMessageTransmitter"
      | "queueSetRemoteRouter"
      | "queueUpgrade"
      | "remoteRouter"
      | "renounceOwnership"
      | "setMinTimelock"
      | "setTimelock"
      | "timelock"
      | "transferOwnership"
      | "unpause"
      | "upgradeToAndCall"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionCancelled"
      | "ActionCommitted"
      | "ActionQueued"
      | "DepositForBurn"
      | "FeeConfigChangeQueued"
      | "FeeConfigUpdated"
      | "Initialized"
      | "LocalTokenChangeQueued"
      | "LocalTokenUpdated"
      | "MessageTransmitterChangeQueued"
      | "MessageTransmitterUpdated"
      | "MinTimelockUpdated"
      | "MintAndWithdraw"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
      | "Paused"
      | "RemoteRouterChangeQueued"
      | "RemoteRouterUpdated"
      | "TimelockUpdated"
      | "Unpaused"
      | "UpgradeCommitted"
      | "UpgradeQueued"
      | "Upgraded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "MAX_FEE_BPS",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MAX_TIMELOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MIN_FLOOR_TIMELOCK",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "bodyVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cancel",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "commitSetFeeConfig",
    values: [BigNumberish, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitSetLocalToken",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitSetMessageTransmitter",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitSetRemoteRouter",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "commitUpgrade",
    values: [BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForBurn",
    values: [BigNumberish, BigNumberish, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositForBurnWithCaller",
    values: [BigNumberish, BigNumberish, BytesLike, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "feeBps", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeRecipient",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "handleReceiveMessage",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "localToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "messageTransmitter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "minTimelock",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingAction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "queueSetFeeConfig",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queueSetLocalToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queueSetMessageTransmitter",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queueSetRemoteRouter",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queueUpgrade",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "remoteRouter",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setMinTimelock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTimelock",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "timelock", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "MAX_FEE_BPS",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MAX_TIMELOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MIN_FLOOR_TIMELOCK",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bodyVersion",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cancel", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "commitSetFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitSetLocalToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitSetMessageTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitSetRemoteRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "commitUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositForBurn",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositForBurnWithCaller",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "feeBps", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeRecipient",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "handleReceiveMessage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "localToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "messageTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "minTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueSetFeeConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueSetLocalToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueSetMessageTransmitter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueSetRemoteRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueUpgrade",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "remoteRouter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMinTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTimelock",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "timelock", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
}

export namespace ActionCancelledEvent {
  export type InputTuple = [actionId: BigNumberish, actionHash: BytesLike];
  export type OutputTuple = [actionId: bigint, actionHash: string];
  export interface OutputObject {
    actionId: bigint;
    actionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionCommittedEvent {
  export type InputTuple = [actionId: BigNumberish, actionHash: BytesLike];
  export type OutputTuple = [actionId: bigint, actionHash: string];
  export interface OutputObject {
    actionId: bigint;
    actionHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionQueuedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    actionHash: BytesLike,
    eta: BigNumberish
  ];
  export type OutputTuple = [actionId: bigint, actionHash: string, eta: bigint];
  export interface OutputObject {
    actionId: bigint;
    actionHash: string;
    eta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositForBurnEvent {
  export type InputTuple = [
    nonce: BigNumberish,
    burnToken: AddressLike,
    amount: BigNumberish,
    depositor: AddressLike,
    mintRecipient: BytesLike,
    destinationDomain: BigNumberish,
    destinationRouter: BytesLike,
    destinationCaller: BytesLike
  ];
  export type OutputTuple = [
    nonce: bigint,
    burnToken: string,
    amount: bigint,
    depositor: string,
    mintRecipient: string,
    destinationDomain: bigint,
    destinationRouter: string,
    destinationCaller: string
  ];
  export interface OutputObject {
    nonce: bigint;
    burnToken: string;
    amount: bigint;
    depositor: string;
    mintRecipient: string;
    destinationDomain: bigint;
    destinationRouter: string;
    destinationCaller: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeConfigChangeQueuedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    newFeeBps: BigNumberish,
    newFeeRecipient: AddressLike
  ];
  export type OutputTuple = [
    actionId: bigint,
    newFeeBps: bigint,
    newFeeRecipient: string
  ];
  export interface OutputObject {
    actionId: bigint;
    newFeeBps: bigint;
    newFeeRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeeConfigUpdatedEvent {
  export type InputTuple = [
    previousFeeBps: BigNumberish,
    currentFeeBps: BigNumberish,
    previousFeeRecipient: AddressLike,
    currentFeeRecipient: AddressLike
  ];
  export type OutputTuple = [
    previousFeeBps: bigint,
    currentFeeBps: bigint,
    previousFeeRecipient: string,
    currentFeeRecipient: string
  ];
  export interface OutputObject {
    previousFeeBps: bigint;
    currentFeeBps: bigint;
    previousFeeRecipient: string;
    currentFeeRecipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LocalTokenChangeQueuedEvent {
  export type InputTuple = [actionId: BigNumberish, newToken: AddressLike];
  export type OutputTuple = [actionId: bigint, newToken: string];
  export interface OutputObject {
    actionId: bigint;
    newToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LocalTokenUpdatedEvent {
  export type InputTuple = [previous: AddressLike, current: AddressLike];
  export type OutputTuple = [previous: string, current: string];
  export interface OutputObject {
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageTransmitterChangeQueuedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    newTransmitter: AddressLike
  ];
  export type OutputTuple = [actionId: bigint, newTransmitter: string];
  export interface OutputObject {
    actionId: bigint;
    newTransmitter: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MessageTransmitterUpdatedEvent {
  export type InputTuple = [previous: AddressLike, current: AddressLike];
  export type OutputTuple = [previous: string, current: string];
  export interface OutputObject {
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MinTimelockUpdatedEvent {
  export type InputTuple = [previous: BigNumberish, current: BigNumberish];
  export type OutputTuple = [previous: bigint, current: bigint];
  export interface OutputObject {
    previous: bigint;
    current: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MintAndWithdrawEvent {
  export type InputTuple = [
    mintRecipient: AddressLike,
    amount: BigNumberish,
    mintToken: AddressLike
  ];
  export type OutputTuple = [
    mintRecipient: string,
    amount: bigint,
    mintToken: string
  ];
  export interface OutputObject {
    mintRecipient: string;
    amount: bigint;
    mintToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoteRouterChangeQueuedEvent {
  export type InputTuple = [
    actionId: BigNumberish,
    domain: BigNumberish,
    router: BytesLike
  ];
  export type OutputTuple = [actionId: bigint, domain: bigint, router: string];
  export interface OutputObject {
    actionId: bigint;
    domain: bigint;
    router: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RemoteRouterUpdatedEvent {
  export type InputTuple = [
    domain: BigNumberish,
    previous: BytesLike,
    current: BytesLike
  ];
  export type OutputTuple = [domain: bigint, previous: string, current: string];
  export interface OutputObject {
    domain: bigint;
    previous: string;
    current: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TimelockUpdatedEvent {
  export type InputTuple = [previous: BigNumberish, current: BigNumberish];
  export type OutputTuple = [previous: bigint, current: bigint];
  export interface OutputObject {
    previous: bigint;
    current: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeCommittedEvent {
  export type InputTuple = [actionId: BigNumberish, newImpl: AddressLike];
  export type OutputTuple = [actionId: bigint, newImpl: string];
  export interface OutputObject {
    actionId: bigint;
    newImpl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradeQueuedEvent {
  export type InputTuple = [actionId: BigNumberish, newImpl: AddressLike];
  export type OutputTuple = [actionId: bigint, newImpl: string];
  export interface OutputObject {
    actionId: bigint;
    newImpl: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TokenMessenger extends BaseContract {
  connect(runner?: ContractRunner | null): TokenMessenger;
  waitForDeployment(): Promise<this>;

  interface: TokenMessengerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  MAX_FEE_BPS: TypedContractMethod<[], [bigint], "view">;

  MAX_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  MIN_FLOOR_TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  bodyVersion: TypedContractMethod<[], [bigint], "view">;

  cancel: TypedContractMethod<[actionId: BigNumberish], [void], "nonpayable">;

  commitSetFeeConfig: TypedContractMethod<
    [
      actionId: BigNumberish,
      newFeeBps: BigNumberish,
      newFeeRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  commitSetLocalToken: TypedContractMethod<
    [actionId: BigNumberish, newToken: AddressLike],
    [void],
    "nonpayable"
  >;

  commitSetMessageTransmitter: TypedContractMethod<
    [actionId: BigNumberish, newTransmitter: AddressLike],
    [void],
    "nonpayable"
  >;

  commitSetRemoteRouter: TypedContractMethod<
    [actionId: BigNumberish, domain: BigNumberish, router: BytesLike],
    [void],
    "nonpayable"
  >;

  commitUpgrade: TypedContractMethod<
    [actionId: BigNumberish, newImpl: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;

  depositForBurn: TypedContractMethod<
    [
      amount: BigNumberish,
      destinationDomain: BigNumberish,
      mintRecipient: BytesLike,
      burnToken: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;

  depositForBurnWithCaller: TypedContractMethod<
    [
      amount: BigNumberish,
      destinationDomain: BigNumberish,
      mintRecipient: BytesLike,
      burnToken: AddressLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  feeBps: TypedContractMethod<[], [bigint], "view">;

  feeRecipient: TypedContractMethod<[], [string], "view">;

  handleReceiveMessage: TypedContractMethod<
    [sourceDomain: BigNumberish, sender: BytesLike, messageBody: BytesLike],
    [boolean],
    "nonpayable"
  >;

  initialize: TypedContractMethod<
    [
      messageTransmitter_: AddressLike,
      localToken_: AddressLike,
      owner_: AddressLike,
      initialTimelock: BigNumberish,
      initialMinTimelock: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  localToken: TypedContractMethod<[], [string], "view">;

  messageTransmitter: TypedContractMethod<[], [string], "view">;

  minTimelock: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingAction: TypedContractMethod<
    [actionId: BigNumberish],
    [TimelockedUpgradeable.PendingActionStructOutput],
    "view"
  >;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  queueSetFeeConfig: TypedContractMethod<
    [newFeeBps: BigNumberish, newFeeRecipient: AddressLike],
    [bigint],
    "nonpayable"
  >;

  queueSetLocalToken: TypedContractMethod<
    [newToken: AddressLike],
    [bigint],
    "nonpayable"
  >;

  queueSetMessageTransmitter: TypedContractMethod<
    [newTransmitter: AddressLike],
    [bigint],
    "nonpayable"
  >;

  queueSetRemoteRouter: TypedContractMethod<
    [domain: BigNumberish, router: BytesLike],
    [bigint],
    "nonpayable"
  >;

  queueUpgrade: TypedContractMethod<
    [newImpl: AddressLike, data: BytesLike],
    [bigint],
    "nonpayable"
  >;

  remoteRouter: TypedContractMethod<[domain: BigNumberish], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setMinTimelock: TypedContractMethod<
    [newMin: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTimelock: TypedContractMethod<[newTl: BigNumberish], [void], "nonpayable">;

  timelock: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "MAX_FEE_BPS"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MAX_TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "MIN_FLOOR_TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bodyVersion"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "cancel"
  ): TypedContractMethod<[actionId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "commitSetFeeConfig"
  ): TypedContractMethod<
    [
      actionId: BigNumberish,
      newFeeBps: BigNumberish,
      newFeeRecipient: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitSetLocalToken"
  ): TypedContractMethod<
    [actionId: BigNumberish, newToken: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitSetMessageTransmitter"
  ): TypedContractMethod<
    [actionId: BigNumberish, newTransmitter: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitSetRemoteRouter"
  ): TypedContractMethod<
    [actionId: BigNumberish, domain: BigNumberish, router: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "commitUpgrade"
  ): TypedContractMethod<
    [actionId: BigNumberish, newImpl: AddressLike, data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositForBurn"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      destinationDomain: BigNumberish,
      mintRecipient: BytesLike,
      burnToken: AddressLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositForBurnWithCaller"
  ): TypedContractMethod<
    [
      amount: BigNumberish,
      destinationDomain: BigNumberish,
      mintRecipient: BytesLike,
      burnToken: AddressLike,
      destinationCaller: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "feeBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "feeRecipient"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "handleReceiveMessage"
  ): TypedContractMethod<
    [sourceDomain: BigNumberish, sender: BytesLike, messageBody: BytesLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      messageTransmitter_: AddressLike,
      localToken_: AddressLike,
      owner_: AddressLike,
      initialTimelock: BigNumberish,
      initialMinTimelock: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "localToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "messageTransmitter"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "minTimelock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingAction"
  ): TypedContractMethod<
    [actionId: BigNumberish],
    [TimelockedUpgradeable.PendingActionStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "queueSetFeeConfig"
  ): TypedContractMethod<
    [newFeeBps: BigNumberish, newFeeRecipient: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "queueSetLocalToken"
  ): TypedContractMethod<[newToken: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "queueSetMessageTransmitter"
  ): TypedContractMethod<[newTransmitter: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "queueSetRemoteRouter"
  ): TypedContractMethod<
    [domain: BigNumberish, router: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "queueUpgrade"
  ): TypedContractMethod<
    [newImpl: AddressLike, data: BytesLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "remoteRouter"
  ): TypedContractMethod<[domain: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMinTimelock"
  ): TypedContractMethod<[newMin: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTimelock"
  ): TypedContractMethod<[newTl: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "timelock"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  getEvent(
    key: "ActionCancelled"
  ): TypedContractEvent<
    ActionCancelledEvent.InputTuple,
    ActionCancelledEvent.OutputTuple,
    ActionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ActionCommitted"
  ): TypedContractEvent<
    ActionCommittedEvent.InputTuple,
    ActionCommittedEvent.OutputTuple,
    ActionCommittedEvent.OutputObject
  >;
  getEvent(
    key: "ActionQueued"
  ): TypedContractEvent<
    ActionQueuedEvent.InputTuple,
    ActionQueuedEvent.OutputTuple,
    ActionQueuedEvent.OutputObject
  >;
  getEvent(
    key: "DepositForBurn"
  ): TypedContractEvent<
    DepositForBurnEvent.InputTuple,
    DepositForBurnEvent.OutputTuple,
    DepositForBurnEvent.OutputObject
  >;
  getEvent(
    key: "FeeConfigChangeQueued"
  ): TypedContractEvent<
    FeeConfigChangeQueuedEvent.InputTuple,
    FeeConfigChangeQueuedEvent.OutputTuple,
    FeeConfigChangeQueuedEvent.OutputObject
  >;
  getEvent(
    key: "FeeConfigUpdated"
  ): TypedContractEvent<
    FeeConfigUpdatedEvent.InputTuple,
    FeeConfigUpdatedEvent.OutputTuple,
    FeeConfigUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "LocalTokenChangeQueued"
  ): TypedContractEvent<
    LocalTokenChangeQueuedEvent.InputTuple,
    LocalTokenChangeQueuedEvent.OutputTuple,
    LocalTokenChangeQueuedEvent.OutputObject
  >;
  getEvent(
    key: "LocalTokenUpdated"
  ): TypedContractEvent<
    LocalTokenUpdatedEvent.InputTuple,
    LocalTokenUpdatedEvent.OutputTuple,
    LocalTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MessageTransmitterChangeQueued"
  ): TypedContractEvent<
    MessageTransmitterChangeQueuedEvent.InputTuple,
    MessageTransmitterChangeQueuedEvent.OutputTuple,
    MessageTransmitterChangeQueuedEvent.OutputObject
  >;
  getEvent(
    key: "MessageTransmitterUpdated"
  ): TypedContractEvent<
    MessageTransmitterUpdatedEvent.InputTuple,
    MessageTransmitterUpdatedEvent.OutputTuple,
    MessageTransmitterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MinTimelockUpdated"
  ): TypedContractEvent<
    MinTimelockUpdatedEvent.InputTuple,
    MinTimelockUpdatedEvent.OutputTuple,
    MinTimelockUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "MintAndWithdraw"
  ): TypedContractEvent<
    MintAndWithdrawEvent.InputTuple,
    MintAndWithdrawEvent.OutputTuple,
    MintAndWithdrawEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RemoteRouterChangeQueued"
  ): TypedContractEvent<
    RemoteRouterChangeQueuedEvent.InputTuple,
    RemoteRouterChangeQueuedEvent.OutputTuple,
    RemoteRouterChangeQueuedEvent.OutputObject
  >;
  getEvent(
    key: "RemoteRouterUpdated"
  ): TypedContractEvent<
    RemoteRouterUpdatedEvent.InputTuple,
    RemoteRouterUpdatedEvent.OutputTuple,
    RemoteRouterUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TimelockUpdated"
  ): TypedContractEvent<
    TimelockUpdatedEvent.InputTuple,
    TimelockUpdatedEvent.OutputTuple,
    TimelockUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeCommitted"
  ): TypedContractEvent<
    UpgradeCommittedEvent.InputTuple,
    UpgradeCommittedEvent.OutputTuple,
    UpgradeCommittedEvent.OutputObject
  >;
  getEvent(
    key: "UpgradeQueued"
  ): TypedContractEvent<
    UpgradeQueuedEvent.InputTuple,
    UpgradeQueuedEvent.OutputTuple,
    UpgradeQueuedEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;

  filters: {
    "ActionCancelled(uint256,bytes32)": TypedContractEvent<
      ActionCancelledEvent.InputTuple,
      ActionCancelledEvent.OutputTuple,
      ActionCancelledEvent.OutputObject
    >;
    ActionCancelled: TypedContractEvent<
      ActionCancelledEvent.InputTuple,
      ActionCancelledEvent.OutputTuple,
      ActionCancelledEvent.OutputObject
    >;

    "ActionCommitted(uint256,bytes32)": TypedContractEvent<
      ActionCommittedEvent.InputTuple,
      ActionCommittedEvent.OutputTuple,
      ActionCommittedEvent.OutputObject
    >;
    ActionCommitted: TypedContractEvent<
      ActionCommittedEvent.InputTuple,
      ActionCommittedEvent.OutputTuple,
      ActionCommittedEvent.OutputObject
    >;

    "ActionQueued(uint256,bytes32,uint64)": TypedContractEvent<
      ActionQueuedEvent.InputTuple,
      ActionQueuedEvent.OutputTuple,
      ActionQueuedEvent.OutputObject
    >;
    ActionQueued: TypedContractEvent<
      ActionQueuedEvent.InputTuple,
      ActionQueuedEvent.OutputTuple,
      ActionQueuedEvent.OutputObject
    >;

    "DepositForBurn(uint64,address,uint256,address,bytes32,uint32,bytes32,bytes32)": TypedContractEvent<
      DepositForBurnEvent.InputTuple,
      DepositForBurnEvent.OutputTuple,
      DepositForBurnEvent.OutputObject
    >;
    DepositForBurn: TypedContractEvent<
      DepositForBurnEvent.InputTuple,
      DepositForBurnEvent.OutputTuple,
      DepositForBurnEvent.OutputObject
    >;

    "FeeConfigChangeQueued(uint256,uint256,address)": TypedContractEvent<
      FeeConfigChangeQueuedEvent.InputTuple,
      FeeConfigChangeQueuedEvent.OutputTuple,
      FeeConfigChangeQueuedEvent.OutputObject
    >;
    FeeConfigChangeQueued: TypedContractEvent<
      FeeConfigChangeQueuedEvent.InputTuple,
      FeeConfigChangeQueuedEvent.OutputTuple,
      FeeConfigChangeQueuedEvent.OutputObject
    >;

    "FeeConfigUpdated(uint256,uint256,address,address)": TypedContractEvent<
      FeeConfigUpdatedEvent.InputTuple,
      FeeConfigUpdatedEvent.OutputTuple,
      FeeConfigUpdatedEvent.OutputObject
    >;
    FeeConfigUpdated: TypedContractEvent<
      FeeConfigUpdatedEvent.InputTuple,
      FeeConfigUpdatedEvent.OutputTuple,
      FeeConfigUpdatedEvent.OutputObject
    >;

    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "LocalTokenChangeQueued(uint256,address)": TypedContractEvent<
      LocalTokenChangeQueuedEvent.InputTuple,
      LocalTokenChangeQueuedEvent.OutputTuple,
      LocalTokenChangeQueuedEvent.OutputObject
    >;
    LocalTokenChangeQueued: TypedContractEvent<
      LocalTokenChangeQueuedEvent.InputTuple,
      LocalTokenChangeQueuedEvent.OutputTuple,
      LocalTokenChangeQueuedEvent.OutputObject
    >;

    "LocalTokenUpdated(address,address)": TypedContractEvent<
      LocalTokenUpdatedEvent.InputTuple,
      LocalTokenUpdatedEvent.OutputTuple,
      LocalTokenUpdatedEvent.OutputObject
    >;
    LocalTokenUpdated: TypedContractEvent<
      LocalTokenUpdatedEvent.InputTuple,
      LocalTokenUpdatedEvent.OutputTuple,
      LocalTokenUpdatedEvent.OutputObject
    >;

    "MessageTransmitterChangeQueued(uint256,address)": TypedContractEvent<
      MessageTransmitterChangeQueuedEvent.InputTuple,
      MessageTransmitterChangeQueuedEvent.OutputTuple,
      MessageTransmitterChangeQueuedEvent.OutputObject
    >;
    MessageTransmitterChangeQueued: TypedContractEvent<
      MessageTransmitterChangeQueuedEvent.InputTuple,
      MessageTransmitterChangeQueuedEvent.OutputTuple,
      MessageTransmitterChangeQueuedEvent.OutputObject
    >;

    "MessageTransmitterUpdated(address,address)": TypedContractEvent<
      MessageTransmitterUpdatedEvent.InputTuple,
      MessageTransmitterUpdatedEvent.OutputTuple,
      MessageTransmitterUpdatedEvent.OutputObject
    >;
    MessageTransmitterUpdated: TypedContractEvent<
      MessageTransmitterUpdatedEvent.InputTuple,
      MessageTransmitterUpdatedEvent.OutputTuple,
      MessageTransmitterUpdatedEvent.OutputObject
    >;

    "MinTimelockUpdated(uint256,uint256)": TypedContractEvent<
      MinTimelockUpdatedEvent.InputTuple,
      MinTimelockUpdatedEvent.OutputTuple,
      MinTimelockUpdatedEvent.OutputObject
    >;
    MinTimelockUpdated: TypedContractEvent<
      MinTimelockUpdatedEvent.InputTuple,
      MinTimelockUpdatedEvent.OutputTuple,
      MinTimelockUpdatedEvent.OutputObject
    >;

    "MintAndWithdraw(address,uint256,address)": TypedContractEvent<
      MintAndWithdrawEvent.InputTuple,
      MintAndWithdrawEvent.OutputTuple,
      MintAndWithdrawEvent.OutputObject
    >;
    MintAndWithdraw: TypedContractEvent<
      MintAndWithdrawEvent.InputTuple,
      MintAndWithdrawEvent.OutputTuple,
      MintAndWithdrawEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RemoteRouterChangeQueued(uint256,uint32,bytes32)": TypedContractEvent<
      RemoteRouterChangeQueuedEvent.InputTuple,
      RemoteRouterChangeQueuedEvent.OutputTuple,
      RemoteRouterChangeQueuedEvent.OutputObject
    >;
    RemoteRouterChangeQueued: TypedContractEvent<
      RemoteRouterChangeQueuedEvent.InputTuple,
      RemoteRouterChangeQueuedEvent.OutputTuple,
      RemoteRouterChangeQueuedEvent.OutputObject
    >;

    "RemoteRouterUpdated(uint32,bytes32,bytes32)": TypedContractEvent<
      RemoteRouterUpdatedEvent.InputTuple,
      RemoteRouterUpdatedEvent.OutputTuple,
      RemoteRouterUpdatedEvent.OutputObject
    >;
    RemoteRouterUpdated: TypedContractEvent<
      RemoteRouterUpdatedEvent.InputTuple,
      RemoteRouterUpdatedEvent.OutputTuple,
      RemoteRouterUpdatedEvent.OutputObject
    >;

    "TimelockUpdated(uint256,uint256)": TypedContractEvent<
      TimelockUpdatedEvent.InputTuple,
      TimelockUpdatedEvent.OutputTuple,
      TimelockUpdatedEvent.OutputObject
    >;
    TimelockUpdated: TypedContractEvent<
      TimelockUpdatedEvent.InputTuple,
      TimelockUpdatedEvent.OutputTuple,
      TimelockUpdatedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UpgradeCommitted(uint256,address)": TypedContractEvent<
      UpgradeCommittedEvent.InputTuple,
      UpgradeCommittedEvent.OutputTuple,
      UpgradeCommittedEvent.OutputObject
    >;
    UpgradeCommitted: TypedContractEvent<
      UpgradeCommittedEvent.InputTuple,
      UpgradeCommittedEvent.OutputTuple,
      UpgradeCommittedEvent.OutputObject
    >;

    "UpgradeQueued(uint256,address)": TypedContractEvent<
      UpgradeQueuedEvent.InputTuple,
      UpgradeQueuedEvent.OutputTuple,
      UpgradeQueuedEvent.OutputObject
    >;
    UpgradeQueued: TypedContractEvent<
      UpgradeQueuedEvent.InputTuple,
      UpgradeQueuedEvent.OutputTuple,
      UpgradeQueuedEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
  };
}
