[package]
name = "token_messenger"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "token_messenger"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = [
    "anchor-lang/idl-build",
    "message_transmitter/idl-build",
    "stable_naira/idl-build",
]
anchor-debug = []
custom-heap = []
custom-panic = []


[dependencies]
anchor-lang = { version = "1.0.2", features = ["init-if-needed"] }
anchor-spl = { version = "1.0.2", features = ["token_2022"] }
message_transmitter = { path = "../message_transmitter", features = ["cpi"] }
stable_naira = { path = "../stable_naira", features = ["cpi"] }

[dev-dependencies]
anchor-lang = "1.0.2"
litesvm = "0.10.0"
solana-message = "3.0.1"
solana-transaction = "3.0.2"
solana-signer = "3.0.0"
solana-keypair = "3.0.1"
solana-instruction = "3.0.0"
solana-pubkey = "3.0.0"
libsecp256k1 = "0.7.1"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
message_transmitter = { path = "../message_transmitter", features = ["cpi"] }
stable_naira = { path = "../stable_naira", features = ["cpi"] }
validator_registry = { path = "../validator_registry", features = ["cpi"] }


[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("solana"))'] }
