/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IMessageHandler,
  IMessageHandlerInterface,
} from "../../../../contracts/cctp/interfaces/IMessageHandler";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32",
        name: "sourceDomain",
        type: "uint32",
      },
      {
        internalType: "bytes32",
        name: "sender",
        type: "bytes32",
      },
      {
        internalType: "bytes",
        name: "messageBody",
        type: "bytes",
      },
    ],
    name: "handleReceiveMessage",
    outputs: [
      {
        internalType: "bool",
        name: "success",
        type: "bool",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IMessageHandler__factory {
  static readonly abi = _abi;
  static createInterface(): IMessageHandlerInterface {
    return new Interface(_abi) as IMessageHandlerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IMessageHandler {
    return new Contract(address, _abi, runner) as unknown as IMessageHandler;
  }
}
