/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { BurnMessage__factory } from "./BurnMessage__factory";
export { Bytes32Address__factory } from "./Bytes32Address__factory";
export { Message__factory } from "./Message__factory";
